/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _Migrations {
  applied_at: Generated<string>;
  filename: string | null;
}

export interface Accounts {
  created_at: Generated<string>;
  current_balance: Generated<number>;
  deleted_at: string | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  name: string;
  opening_balance: Generated<number>;
  type: string;
}

export interface AccountTransactions {
  account_id: number;
  amount: number;
  created_at: Generated<string>;
  created_by: number | null;
  date: Generated<string>;
  description: string | null;
  id: Generated<number>;
  reference_id: number | null;
  reference_type: 'sale' | 'purchase' | 'payment' | 'expense' | 'transfer' | 'adjustment' | 'capital' | 'withdrawal' | null;
  type: string;
}

export interface Areas {
  created_at: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  name: string;
}

export interface AuditLog {
  action: string;
  created_at: Generated<string>;
  id: Generated<number>;
  ip_address: string | null;
  new_value: string | null;
  old_value: string | null;
  record_id: number | null;
  table_name: string;
  user_agent: string | null;
  user_id: number | null;
}

export interface BackupLog {
  created_at: Generated<string>;
  destination: string;
  file_path: string;
  id: Generated<number>;
  size_bytes: number | null;
  status: string;
}

export interface BusinessSettings {
  address: string | null;
  business_name: Generated<string>;
  currency_symbol: Generated<string>;
  id: Generated<number>;
  logo_path: string | null;
  low_stock_threshold_default: Generated<number>;
  phone: string | null;
  printer_interface: string | null;
  printer_type: Generated<string>;
  printer_width: Generated<number>;
  receipt_footer: Generated<string | null>;
  theme: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<string>;
}

export interface Categories {
  created_at: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  description: string | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  name: string;
}

export interface CtnTransactions {
  change_qty: number;
  created_at: Generated<string>;
  created_by: number | null;
  customer_id: number;
  id: Generated<number>;
  note: string | null;
  reference_id: number | null;
  reference_type: string | null;
}

export interface Customers {
  address: string | null;
  balance: Generated<number>;
  created_at: Generated<string>;
  ctn_balance: Generated<number>;
  deleted_at: string | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  name: string;
  phone: string | null;
  shop_name: string | null;
  updated_at: Generated<string>;
}

export interface ExpenseCategories {
  deleted_at: string | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  name: string;
}

export interface Expenses {
  account_id: number | null;
  amount: number;
  category_id: number | null;
  created_at: Generated<string>;
  created_by: number | null;
  date: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  note: string | null;
  sale_id: number | null;
  van_assignment_id: number | null;
}

export interface Items {
  barcode: string | null;
  category_id: number | null;
  cost_price: Generated<number>;
  created_at: Generated<string>;
  current_stock: Generated<number>;
  deleted_at: string | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_active: Generated<number>;
  is_deleted: Generated<number>;
  low_stock_threshold: Generated<number>;
  name: string;
  packaging: string | null;
  selling_price: number;
  size: string | null;
  supplier_id: number | null;
  units_per_ctn: Generated<number>;
  updated_at: Generated<string>;
  variant: string | null;
}

export interface Payments {
  account_id: number | null;
  amount: number;
  created_at: Generated<string>;
  created_by: number | null;
  date: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  direction: string;
  id: Generated<number>;
  is_deleted: Generated<number>;
  method: string;
  note: string | null;
  party_id: number;
  party_type: string;
  reference_id: number | null;
  reference_type: string | null;
}

export interface PaymentAllocations {
  id: Generated<number>;
  payment_id: number;
  reference_type: string;
  reference_id: number;
  amount: number;
  created_at: Generated<string>;
}

export interface PurchaseItems {
  id: Generated<number>;
  item_id: number;
  line_total: number;
  purchase_id: number;
  qty: number;
  unit_cost: number;
}

export interface Purchases {
  created_at: Generated<string>;
  created_by: number | null;
  date: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  discount: Generated<number>;
  due_date: string | null;
  id: Generated<number>;
  invoice_no: string;
  is_deleted: Generated<number>;
  net_total: number;
  paid_amount: Generated<number>;
  status: Generated<string>;
  subtotal: number;
  supplier_id: number;
  updated_at: string | null;
}

export interface Routes {
  area_id: number | null;
  created_at: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  name: string;
}

export interface SaleItems {
  cost_price_snapshot: Generated<number>;
  id: Generated<number>;
  item_id: number;
  line_total: number;
  qty: number;
  sale_id: number;
  unit_price: number;
}

export interface Sales {
  created_at: Generated<string>;
  created_by: number | null;
  customer_id: number | null;
  date: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  discount: Generated<number>;
  due_date: string | null;
  id: Generated<number>;
  invoice_no: string;
  is_deleted: Generated<number>;
  net_total: number;
  paid_amount: Generated<number>;
  sale_type: Generated<string>;
  status: Generated<string>;
  subtotal: number;
  updated_at: string | null;
  van_assignment_id: number | null;
}

export interface SaleReturnItems {
  id: Generated<number>;
  return_id: number;
  sale_item_id: number;
  item_id: number;
  qty: number;
  unit_price: number;
  line_total: number;
}

export interface SaleReturns {
  id: Generated<number>;
  return_no: string;
  sale_id: number;
  customer_id: number | null;
  date: Generated<string>;
  total_amount: Generated<number>;
  refund_amount: Generated<number>;
  credit_amount: Generated<number>;
  status: Generated<string>;
  created_by: number | null;
  created_at: Generated<string>;
}

export interface StockAdjustments {
  change_qty: number;
  cost_price_snapshot: Generated<number>;
  total_value: Generated<number>;
  created_at: Generated<string>;
  created_by: number | null;
  id: Generated<number>;
  item_id: number;
  note: string | null;
  reason: string;
}

export interface StockMovements {
  change_qty: number;
  created_at: Generated<string>;
  created_by: number | null;
  id: Generated<number>;
  item_id: number;
  note: string | null;
  reference_id: number | null;
  reference_type: string | null;
  type: string;
}

export interface Suppliers {
  address: string | null;
  balance: Generated<number>;
  created_at: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  name: string;
  phone: string | null;
  updated_at: Generated<string>;
}

export interface Users {
  address: string | null;
  created_at: Generated<string>;
  deleted_at: string | null;
  deleted_by: number | null;
  full_name: string;
  id: Generated<number>;
  is_active: Generated<number>;
  is_deleted: Generated<number>;
  password_hash: string;
  phone: string | null;
  role: Generated<string>;
  updated_at: Generated<string>;
  username: string;
}

export interface VanAssignmentItems {
  id: Generated<number>;
  item_id: number;
  qty_loaded: number;
  qty_returned: Generated<number>;
  van_assignment_id: number;
}

export interface VanAssignments {
  created_at: Generated<string>;
  created_by: number | null;
  date: Generated<string>;
  id: Generated<number>;
  notes: string | null;
  route_id: number | null;
  status: Generated<string>;
  van_salesman_id: number;
}

export interface DB {
  _migrations: _Migrations;
  account_transactions: AccountTransactions;
  accounts: Accounts;
  areas: Areas;
  audit_log: AuditLog;
  backup_log: BackupLog;
  business_settings: BusinessSettings;
  categories: Categories;
  ctn_transactions: CtnTransactions;
  customers: Customers;
  expense_categories: ExpenseCategories;
  expenses: Expenses;
  items: Items;
  payment_allocations: PaymentAllocations;
  payments: Payments;
  purchase_items: PurchaseItems;
  purchases: Purchases;
  routes: Routes;
  sale_items: SaleItems;
  sale_return_items: SaleReturnItems;
  sale_returns: SaleReturns;
  sales: Sales;
  stock_adjustments: StockAdjustments;
  stock_movements: StockMovements;
  suppliers: Suppliers;
  users: Users;
  van_assignment_items: VanAssignmentItems;
  van_assignments: VanAssignments;
}
